//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by JDsClipboardTester.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define ID_TEXT_SERIALIZATION_STORE_MEM 32775
#define ID_TEXT_SERIALIZATION_LOAD_MEM  32776
#define ID_VIEW_CLEAR                   32777
#define ID_VIEW_PROPERTIES              32778
#define ID_TEXT_SERIALIZATION_STORE_FILE 32779
#define ID_TEXT_SERIALIZATION_LOAD_FILE 32780
#define ID_SERIALIZATION_TEXT           32784
#define ID_SERIALIZATION_IMAGE          32785
#define ID_IMAGE_SERIALIZATION_SERIALIZE_MEM 32786
#define ID_IMAGE_SERIALIZATION_LOAD_MEM 32787
#define ID_IMAGE_SERIALIZATION_STORE_MEM 32788
#define ID_IMAGE_SERIALIZATION_STORE_TO_FILE 32789
#define ID_IMAGE_SERIALIZATION_LOAD_FROM_FILE 32790
#define ID_TOOLS_RUNJDSRDPCLIP          32793
#define ID_TOOLS_CLOSEJDSRDPCLIP        32794

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        201
#define _APS_NEXT_COMMAND_VALUE         32795
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
