#include "StdAfx.h"
#include "resource.h"
#include "AboutDlg.h"


LRESULT CAboutDlg::OnOptionsCpu(WORD /*wNotifyCode*/, WORD /*wID*/, HWND /*hWndCtl*/, BOOL& /*bHandled*/)
{
	// TODO: Add your command handler code here

	return 0;
}


LRESULT CAboutDlg::OnOptionsGetdiskdefragmentationinfo(WORD /*wNotifyCode*/, WORD /*wID*/, HWND /*hWndCtl*/, BOOL& /*bHandled*/)
{
	// TODO: Add your command handler code here
	return 0;
}
